environment:
  global:
    CRATE_NAME: itm
    DEPLOY_VERSION: stable
    RUST_VERSION: stable
  matrix:
    - TARGET: i686-pc-windows-gnu
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: ci\install.ps1

build: false

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% &&
      cargo build --target %TARGET% --release &&
      cargo test --target %TARGET% &&
      cargo test --target %TARGET% --release
    ) else (
      if [%RUST_VERSION%]==[%DEPLOY_VERSION%] (
        cargo rustc --target %TARGET% --release --bin itmdump -- -C lto
      )
    )

before_deploy:
  - ps: ci\package.ps1

deploy:
  description: 'Windows release'
  artifact: /.*\.zip/
  auth_token:
    secure: bQ29dEXeNG5VP2hQcWiZ1xsfmkGosteCDNeYu/cXTX4lOeghOp0qANpQXmGfal29
  provider: GitHub
  on:
    # NOTE this "version" must match %DEPLOY_VERSION% (see top)
    RUST_VERSION: stable
    appveyor_repo_tag: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - try

notifications:
  - provider: Email
    on_build_success: false
